[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_lottery_anchor = "BehPGKepmq9Lke8JtqAmX1cjF2fquReo8yX4ZXJNbfyU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sujoynath/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
